Expose connecting player's UUID in the PreLoginEvent
PaperMC/Velocity pull request #1009
Opened 2023-05-11 17:36 UTC by kezz

Unsure if docs need to be more specific, or if the old event constructor should be deprecated/removed.

2023-05-12 12:54 UTC, 0utplay commented
I think using `uniqueId` as field, parameter and getter name is more appropriate as the API usally uses that for any uuids.

https://github.com/PaperMC/Velocity/blob/7f776abf550001186a1f11f4e5ff760dd66e3b04/api/src/main/java/com/velocitypowered/api/proxy/Player.java#L75

2023-05-14 05:29 UTC, astei requested changes

2023-05-14 05:29 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/ServerLogin.java
> +import java.util.Objects;
Unused import

2023-05-14 05:29 UTC, astei commented on api/src/main/java/com/velocitypowered/api/event/connection/PreLoginEvent.java
> +  }
let's deprecate this

2023-05-14 05:30 UTC, astei requested changes

2023-05-14 05:30 UTC, astei commented on api/src/main/java/com/velocitypowered/api/event/connection/PreLoginEvent.java
> +  public @Nullable UUID getUuid() {
Change this to `getUniqueId()`

2023-06-07 15:12 UTC, kyngs commented
Isn't the GameProfileRequestEvent called after the PreLoginEvent? If yes, what's the point of exposing the UUID even though it still cannot be used for DB purposes?

2023-12-14 16:34 UTC, 456dev commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/InitialLoginSessionHandler.java
> +    PreLoginEvent event = new PreLoginEvent(inbound, login.getUsername(), login.getHolderUuid());
is this the uuid sent by the client?

2024-02-09 15:01 UTC, 4drian3d commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/InitialLoginSessionHandler.java
> +    PreLoginEvent event = new PreLoginEvent(inbound, login.getUsername(), login.getHolderUuid());
Yes

2024-02-09 15:19 UTC, 4drian3d approved these changes

2024-02-09 15:23 UTC, merged