Add -haproxy-protocol startup parameter
PaperMC/Velocity pull request #1136
Opened 2023-11-05 04:27 UTC by BingYanchi

resolves https://github.com/PaperMC/Velocity/issues/1024

2023-11-05 13:01 UTC, powercasgamer requested changes

2023-11-05 13:01 UTC, powercasgamer commented on proxy/src/main/java/com/velocitypowered/proxy/ProxyOptions.java
> +  private final Boolean haproxy;
```suggestion
  private final boolean haproxy;
```

2023-11-05 13:01 UTC, powercasgamer commented on proxy/src/main/java/com/velocitypowered/proxy/ProxyOptions.java
> +  public Boolean isHaproxy() {
```suggestion
  public boolean isHaproxy() {
```

2024-01-18 11:09 UTC, electronicboy commented on proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
> +    if (haproxy != null) {
This is always true, as you declared the method return to be a primative

2024-01-20 16:25 UTC, 4drian3d approved these changes

2024-01-21 15:47 UTC, merged

2024-01-21 16:05 UTC, BingYanchi commented
```
Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
        at joptsimple.ArgumentAcceptingOptionSpec.defaultsTo(ArgumentAcceptingOptionSpec.java:225)
        at com.velocitypowered.proxy.ProxyOptions.<init>(ProxyOptions.java:51)
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:62)
```
There is a problem with this PR and it needs to be rolled back.