1.20.3 working & checkstyle fixes
PaperMC/Velocity pull request #1150
Opened 2023-12-06 14:58 UTC by pkt77

Not complete with API, but working

2023-12-06 15:53 UTC, MrPowerGamerBR commented
(copying from my comment in the previous PR because this bug also affects this PR too)
 
One thing that I have noticed while testing is that I cannot login to the server
```
[12:29:44 ERROR]: [server connection] MrPowerGamerBR -> sparklypower_survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@62052405
java.lang.NullPointerException: Cannot invoke "com.velocitypowered.proxy.protocol.packet.chat.ComponentHolder.getComponent()" because the return value of "com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo$Entry.getDisplayName()" is null
        at com.velocitypowered.proxy.tablist.VelocityTabList.processUpsert(VelocityTabList.java:255) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at com.velocitypowered.proxy.tablist.VelocityTabList.processUpdate(VelocityTabList.java:205) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handle(BackendPlaySessionHandler.java:281) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo.handle(UpsertPlayerInfo.java:133) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:153) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-proxy-3.2.0-sparklyvelocity-SNAPSHOT-all.jar:3.2.0-sparklyvelocity-SNAPSHOT (git-ba58425d)]
        [...]

2023-12-06 16:23 UTC, pkt77 commented
> I have tested and using `entry.getDisplayName() != null ? entry.getDisplayName().getComponent() : null` does fix the issue and the player is able to login without any issues

Thanks, guess you had an NPC with no display name?

2023-12-06 16:30 UTC, MrPowerGamerBR commented
> > I have tested and using `entry.getDisplayName() != null ? entry.getDisplayName().getComponent() : null` does fix the issue and the player is able to login without any issues
> 
> Thanks, guess you had an NPC with no display name?

Yup, I use husks with no AI and no display name (the display name of these entities are just random color cores) on my server to create "fake" player NPCs, the entity spawn packets are replaced with player spawn packets, and the player name is "simulated" with scoreboards (to allow 16+ character names)

2023-12-06 18:18 UTC, MrPowerGamerBR commented
Also, I think that disconnect messages are not being sent correctly to 1.20.3 clients

The easiest way to reproduce this is by... not having any online servers! Velocity should kick the player with the `Unable to connect you to sparklypower_survival. Please try again later.` message, but in reality this message shows up when the player is kicked.

![image](https://github.com/PaperMC/Velocity/assets/9496359/b7050558-a7ed-4bc0-81c4-9989fd060946)

However, I'm not sure if this is 100% related to *only* kick messages, I was online on my server and after a while I was kicked with the same error message, and sadly there isn't any logs in Velocity nor in Paper. Sadly I'm also not sure what triggers this issue on my server, but maybe it is a packet that is also using the new NBT messages? (I'm using ViaVersion on my 1.20.2 backend servers tho, could be something related to this)

2023-12-06 18:31 UTC, powercasgamer commented on proxy/src/main/java/com/velocitypowered/proxy/tablist/VelocityTabList.java
> +      currentEntry.setDisplayNameWithoutUpdate(entry.getDisplayName() != null ? entry.getDisplayName().getComponent() : null);
checkstyle fails here

2023-12-06 19:54 UTC, pkt77 commented
> Also, I think that disconnect messages are not being sent correctly to 1.20.3 clients

Fixed, but I don't like it. Mojang in their infinite wisdom kept the Login Disconnect as JSON, but everything else is NBT.
I'm passing in version 1.20.2 to ComponentHolder for Logins, hopefully someone else can make a better solution.

2023-12-07 06:17 UTC, Pantera07 commented
When I send a message or actionbar using Velocity plugins, I get an error.
![test](https://github.com/PaperMC/Velocity/assets/89838384/2f5acd3c-218a-49b4-a2e8-12788efd727b)

2023-12-07 06:20 UTC, wgaylord commented
> > Also, I think that disconnect messages are not being sent correctly to 1.20.3 clients
> 
> Fixed, but I don't like it. Mojang in their infinite wisdom kept the Login Disconnect as JSON, but everything else is NBT. I'm passing in version 1.20.2 to ComponentHolder for Logins, hopefully someone else can make a better solution.

This was so older clients could still get a valid disconnect message when they tried to connect to an up to date server.

2023-12-07 07:09 UTC, Pantera07 commented
> When I send a message or actionbar using Velocity plugins, I get an error.

This can be reproduced by typing `/velocity`. (can be reproduced without plugin)

2023-12-07 11:05 UTC, SamB440 commented
Can you disable the 1.20.2 handling in ConfigSessionHandler where Velocity resends resourcepacks on server switch? I don't think it should be needed in 1.20.3 anymore and I want to be able to control this via a plugin.

2023-12-07 14:58 UTC, Pantera07 commented
If I move to another backend server I get the error. (client version lower than 1.20.2)
Tested with versions 1.19.4 and 1.20.1.
This can be reproduced with the `/server ~` command.

```
[23:53:28 INFO]: [connected player] Mad_Daniel (/127.0.0.1:7297) has disconnected: An internal error occurred in your connection.
[23:53:28 ERROR]: [connected player] Mad_Daniel (/127.0.0.1:7297): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@1a8e36ae
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.velocitypowered.api.network.ProtocolVersion.compareTo(java.lang.Enum)" because "this.version" is null
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:230) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.connection.client.ConnectedPlayer.clearPlayerListHeaderAndFooter(ConnectedPlayer.java:546) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.handle(TransitionSessionHandler.java:108) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.protocol.packet.JoinGame.handle(JoinGame.java:476) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-0dfbb144)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-proxy-3.2.0 [...]

2023-12-07 15:49 UTC, Pantera07 commented
1.20.4 is released.

https://github.com/pkt77/Velocity/blob/2fc151f700076463b1cda9fe26b292b288f8721d/api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java#L67
```
  MINECRAFT_1_20_3(765, "1.20.3", "1.20.4");
```

2023-12-07 16:37 UTC, Pantera07 commented
If I connect to the backend server and then immediately disconnect (trying to connect to a whitelisted server or a banned server) I get an error. (1.20.3 Client)

```
[01:33:35 INFO]: [server connection] Mad_Daniel -> survival has connected
[01:33:35 ERROR]: [server connection] Mad_Daniel -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.LoginSessionHandler@50454533
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.Disconnect Direction CLIENTBOUND Protocol 1.20.3 State LOGIN ID 0
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 13
        at com.velocitypowered.proxy.protocol.ProtocolUtils.readBinaryTag(ProtocolUtils.java:398) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at com.velocitypowered.proxy.protocol.packet.chat.ComponentHolder.read(ComponentHolder.java:281) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at com.velocitypowered.proxy.protocol.packet.Disconnect.decode(Disconnect.java:61) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        ... 26 more
[01:33:35 INFO]: [server connection] Mad_Daniel -> survival has disconnected
[01:33:35 ERROR]: [connected player] Mad_Daniel (/127.0.0.1:18192): unable to connect to server survival
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.Disconnect Direction CLIENTBOUND Protocol 1.20.3 State LOGIN ID 0
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-2fc151f7)]
        at  [...]

2023-12-08 04:15 UTC, 4drian3d commented
I was testing this branch, but it seems that for 1.20.3/4 clients the PlayerChatEvent does not run at all, in 1.20.2 and lower versions everything works normally

2023-12-08 06:56 UTC, Pantera07 commented
https://github.com/PaperMC/Velocity/blob/7774e993b66f0638576ee10788001512a75edd66/proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java#L214

2023-12-08 08:10 UTC, powercasgamer requested changes

2023-12-08 08:10 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/player/PlayerResourcePackStatusEvent.java
> +    public boolean isIntermediate() {
javadoc

2023-12-09 19:22 UTC, electronicboy commented
So, my understanding is that this is currently working bar the lack of the API for resource packs?
if so, I've bumped us to 3.3.x so that we can start looking at internals breaks and deprecating some aspects of the API in order to support this, do we want to merge this into the 3.3.x experimental builds pending the resource pack stuff?

2023-12-10 08:42 UTC, Gerrygames commented
> So, my understanding is that this is currently working bar the lack of the API for resource packs?
> 
> if so, I've bumped us to 3.3.x so that we can start looking at internals breaks and deprecating some aspects of the API in order to support this, do we want to merge this into the 3.3.x experimental builds pending the resource pack stuff?

Yes. I've been testing this on our beta and production servers for a few days now. Everything seems to be working. 

I don't have much time until the weekend so if someone else wants to take a look at implementing new API for resource packs it would be much appreciated.
A few things to take into consideration:
- Behavior of the old API should be kept
- What should getPendingResourcePack and getAppliedResourcePack return? The last resource pack applied via the old API? Ignore everything applied via the new API?
- Should resource packs sent by the backend server be kept after switching to a new server? Imo default behavior should be that resource packs applied by the proxy should be kept and resource packs from the backend server should be removed. Maybe this could be changed in the ServerResourcePackSendEvent. 
- Applying resource packs during configuration state should block entering play state until done.

2023-12-10 23:47 UTC, pop4959 commented
Minor nitpick but should probably also fix code style before changing, seeing a lot of missing line endings, etc. Everything else looks OK resource packs aside, and the obvious todo's around components.

When the new API is added the hard-coded resource pack re-apply for 1.20.2 clients should also be removed.

2023-12-11 10:43 UTC, DartPower commented
I'm encored with error when using a build with this unfinished version:
https://github.com/Elytrium/LimboAPI/issues/127

And also with another few plugins (LimboFilter, MCAuth)
This is very need for me. I can wait but very interesting when it's done :smiley:

2023-12-11 11:07 UTC, powercasgamer commented
> I'm encored with error when using a build with this unfinished version: [Elytrium/LimboAPI#127](https://github.com/Elytrium/LimboAPI/issues/127)
> 
> And also with another few plugins (LimboFilter, MCAuth) This is very need for me. I can wait but very interesting when it's done 😃

This is a plugin issue. Said plugin is using internals.

2023-12-12 12:47 UTC, electronicboy commented on proxy/src/main/java/com/velocitypowered/proxy/connection/backend/ConfigSessionHandler.java
> +    if (player.getProtocolVersion() == ProtocolVersion.MINECRAFT_1_20_2) {
This hack should honestly just be removed, it creates inconsistent behavior on the proxy itself in order to provide support for a version of the client which people will generally move from fast, imho

2023-12-12 12:59 UTC, electronicboy approved these changes
Overall, this looks file, leaves us with a few TODOs regarding API, but, that's going to be partially pending on changes elsewhere as we revisit this

my only real concern is the amount of formatting changes in here creating much extra diff than needed, I don't intend to be a hard stickler on this sorta thing, but, unless this is generally a sane default IDEA formatting config just doing its work, I'd be inclined for this stuff to be cleaned up, otherwise, I'm generally fine on that front in the whole nature of "lets not fight the IDE from producing formatted code, as otherwise it's just a headache"

2023-12-12 22:25 UTC, lucasfrederico approved these changes

2023-12-13 05:44 UTC, MrTommyt commented
Cannot join under 
![image](https://github.com/PaperMC/Velocity/assets/60544121/ccdf1842-e4c1-4bc6-af1f-4bf019434ae1)

When resource pack is enabled on 1.20.4
(resourcepack sent by the server, not the proxy)

2023-12-13 15:51 UTC, merged