Reworking code for Java 17
PaperMC/Velocity pull request #1154
Opened 2023-12-09 20:45 UTC by novitpw

Beginning with Java versions 14 and 16, the "switch" command and the "instanceof" operator have been redesigned. Also in Java 16 a tuple called "record" was added. More information can be found at [JDK Enhancement Proposal](https://openjdk.org/projects/jdk/17/jeps-since-jdk-11) (JEP 361, 394, 395).

2023-12-12 00:07 UTC, 4drian3d approved these changes

2023-12-12 00:39 UTC, Loyisa requested changes

2023-12-12 00:39 UTC, Loyisa commented on native/src/main/java/com/velocitypowered/natives/util/MoreByteBufUtils.java
> +      case DIRECT_PREFERRED, DIRECT_REQUIRED -> alloc.directBuffer(initialCapacity);
```java
default -> throw new AssertionError("Preferred buffer type unknown");
```

2023-12-12 01:06 UTC, novitpw commented on native/src/main/java/com/velocitypowered/natives/util/MoreByteBufUtils.java
> +      case DIRECT_PREFERRED, DIRECT_REQUIRED -> alloc.directBuffer(initialCapacity);
Will never be used. In cases where enama is updated, an error immediately appears stating that the "switch" statement does not cover all possible input values.
![image](https://github.com/PaperMC/Velocity/assets/90355736/a07b1ec7-c146-470b-9efc-45049de7fb91)

2023-12-14 20:42 UTC, 4drian3d commented on proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/GameSpyQueryHandler.java
> +    private ResponseWriter(ByteBuf buf, boolean isBasic) {
To do validations on a constructor of a record, you can simply do this

![image](https://github.com/PaperMC/Velocity/assets/68704415/0f4bb826-b735-405c-a074-e91da44492d9)

2023-12-14 23:27 UTC, 4drian3d approved these changes

2023-12-19 00:43 UTC, ham1255 commented
should fix #1080 i think

2024-01-18 23:29 UTC, RealBauHD approved these changes

2024-01-19 14:35 UTC, RealBauHD commented on api/src/main/java/com/velocitypowered/api/command/CommandManager.java
> +   * @see Command for a list of registrable Command subinterfaces
I don't see any reason for this

2024-01-19 14:35 UTC, RealBauHD commented on api/src/main/java/com/velocitypowered/api/command/CommandManager.java
> +   * @see Command for a list of registrable Command subinterfaces
same here

2024-03-04 21:40 UTC, novitpw commented
It will never be merged...

2024-03-04 21:40 UTC, closed without merging