Cache HttpClients instead of having a single instance
PaperMC/Velocity pull request #1243
Opened 2024-02-13 22:56 UTC by 4drian3d

This would solve a rare ["too many concurrent streams"](https://discord.com/channels/289587909051416579/908507886420910101/1203719351136550962) error.

When Velocity is upgraded to Java 21, this solution could be changed to use a [try-with-resources with the HttpClient](https://docs.oracle.com/en/java/javase/21/docs/api/java.net.http/java/net/http/HttpClient.html) created.

2024-02-13 22:58 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java
>              .executor(this.workerGroup)
can we please remove this - I suspect this is causing #1242

2024-02-14 02:28 UTC, kashike requested changes

2024-02-14 02:28 UTC, kashike commented on proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java
>    public HttpClient getHttpClient() {
```suggestion
  public HttpClient createHttpClient() {
```

2024-02-15 07:38 UTC, kashike approved these changes

2024-02-15 12:03 UTC, electronicboy approved these changes

2024-02-15 14:59 UTC, merged