feat: Add basic API for server links
PaperMC/Velocity pull request #1353
Opened 2024-06-13 10:33 UTC by WiIIiam278

Adds a (very simple) API for setting a list of server links to display to the client with either built-in or component labels. Strings for URLs as is the case in the resource pack API.

I was thinking about doing something more complex with a builder or something, but I'm not sure it's really needed in this case?

2024-06-13 14:46 UTC, RealBauHD requested changes

2024-06-13 14:46 UTC, RealBauHD commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * Send the player a list of custom links to display in their client's pause menu.
There should be a note that it can conflict with backend servers

2024-06-13 14:46 UTC, RealBauHD commented on api/src/main/java/com/velocitypowered/api/util/ServerLink.java
> +  public ServerLink(Component label, String link) {
A static method instead of the constructor like adventure does e. g. `ServerLink#serverLink`

2024-06-13 14:46 UTC, RealBauHD commented on api/src/main/java/com/velocitypowered/api/util/ServerLink.java
> +  public ServerLink(Type type, String link) {
same

2024-06-13 14:46 UTC, RealBauHD commented on api/src/main/java/com/velocitypowered/api/util/ServerLink.java
> +    this.link = URI.create(link).toString();
Would it be convenient if we kept the URI?

2024-06-13 14:46 UTC, RealBauHD commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    connection.write(new ClientboundServerLinksPacket(ImmutableList.copyOf(links).stream()
The stream is a bit clunky

2024-06-13 16:06 UTC, WiIIiam278 commented on api/src/main/java/com/velocitypowered/api/util/ServerLink.java
> +    this.link = URI.create(link).toString();
Sure, can do

2024-06-13 16:08 UTC, WiIIiam278 commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    connection.write(new ClientboundServerLinksPacket(ImmutableList.copyOf(links).stream()
I reduced the clunkiness a bit by making a constructor in the packet ServerLink class. Could make this an array + loop if needed, or something else you had in mind.

2024-06-13 19:39 UTC, alexdev03 commented on api/src/main/java/com/velocitypowered/api/util/ServerLink.java
> +    return new ServerLink(label, link);
There should be a null check here for both arguments

2024-06-13 19:39 UTC, alexdev03 commented on api/src/main/java/com/velocitypowered/api/util/ServerLink.java
> +    return new ServerLink(type, link);
Also here

2024-06-13 19:49 UTC, WiIIiam278 commented
@alexdev03 The link is checked in the constructor above.

2024-06-14 06:54 UTC, novitpw commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    connection.write(new ClientboundServerLinksPacket(ImmutableList.copyOf(links).stream()
Use List#copyOf

2024-06-16 16:09 UTC, 4drian3d approved these changes

2024-06-18 08:56 UTC, powercasgamer approved these changes

2024-06-18 14:29 UTC, merged