feat: Add server registered/unregistered events
PaperMC/Velocity pull request #1386
Opened 2024-07-19 17:53 UTC by Twarug

These events are useful for handling dynamically registered servers by other plugins or reloads of velocity configuration.

This PR replaces #1050, due to owners inactivity.

2024-07-20 06:57 UTC, Timongcraft commented
I think the new API should be annotated with `@Beta`.

2024-07-22 11:21 UTC, kennytv approved these changes

2024-07-24 21:14 UTC, 4drian3d approved these changes
I think these events would be perfect to be created as records, otherwise, lgtm

2024-07-24 22:14 UTC, 4drian3d requested changes

2024-07-24 22:14 UTC, 4drian3d commented on api/src/main/java/com/velocitypowered/api/event/proxy/server/ServerUnregisteredEvent.java
> +public record ServerUnregisteredEvent(@NotNull RegisteredServer unregisteredServer) {
```java
public record ServerUnregisteredEvent(@NotNull RegisteredServer unregisteredServer) {
    ServerUnregisteredEvent {
        Preconditions.checkNotNull(unregisteredServer, "unregisteredServer");
    }
}
```

2024-07-24 22:14 UTC, 4drian3d commented on api/src/main/java/com/velocitypowered/api/event/proxy/server/ServerRegisteredEvent.java
> +public record ServerRegisteredEvent(@NotNull RegisteredServer registeredServer) {
```java
public record ServerRegisteredEvent(@NotNull RegisteredServer registeredServer) {
    ServerRegisteredEvent {
        Preconditions.checkNotNull(registeredServer, "registeredServer");
    }
}
```

2024-07-24 22:56 UTC, 4drian3d approved these changes

2024-07-24 23:01 UTC, powercasgamer requested changes

2024-07-24 23:01 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/proxy/server/ServerRegisteredEvent.java
> + * @param registeredServer A registeredServer that just has been registered.
```suggestion
 * @param registeredServer A {@link RegisteredServer} that has been registered.
```

2024-07-24 23:01 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/proxy/server/ServerUnregisteredEvent.java
> + * @param unregisteredServer A registeredServer that just has been unregistered.
```suggestion
 * @param unregisteredServer A {@link RegisteredServer} that has been unregistered.
```

2024-07-24 23:05 UTC, powercasgamer requested changes

2024-07-24 23:05 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/proxy/server/ServerRegisteredEvent.java
> + *  @see com.velocitypowered.api.proxy.ProxyServer#registerServer(ServerInfo)
```suggestion
 * @see com.velocitypowered.api.proxy.ProxyServer#registerServer(ServerInfo)
```

2024-07-24 23:05 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/proxy/server/ServerUnregisteredEvent.java
> + *  @see com.velocitypowered.api.proxy.ProxyServer#unregisterServer(ServerInfo)
```suggestion
 * @see com.velocitypowered.api.proxy.ProxyServer#unregisterServer(ServerInfo)
```

2024-07-24 23:11 UTC, powercasgamer approved these changes

2024-07-24 23:13 UTC, merged