feat: Add primitive support for sound api
PaperMC/Velocity pull request #1422
Opened 2024-09-03 14:26 UTC by Timongcraft

With this PR, the Adventure-provided sound API is **partially** implemented.

This PR changes the previous behavior of failing all Adventure sound-related methods silently. The newly implemented methods now throw exception patterns similar to other methods.
I don't think compatibility needs to be kept here, as it was previously not implemented. However, this can be reverted if needed.

What this PR implements:
- A method to play back (custom) sounds for a specific player (at the player itself) for players with 1.19.3+
- A method to stop (custom) sounds for players with 1.19.3+

What this PR **doesn't** implements:
- A method to play back (custom) sounds for a specific player at a position or another entity for players of all versions
- A method to play back (custom) sounds (globally) at a specific location for players of all versions
(- A method to play back (custom) sounds for a specific player (at the player itself) for players with 1.19.2 and below)
(- A method to stop (custom) sounds for players with 1.19.2 and below)

2024-09-15 18:47 UTC, Timongcraft commented
TODO:
- [ ] Resolve merge conflicts

2024-12-08 00:01 UTC, nicolube commented
What is the state of this? I would like this feature very much.

2024-12-08 08:17 UTC, Timongcraft commented
From my end, it is finished, although I would think it makes more sense to make the methods fail silently again.

2024-12-08 08:53 UTC, Timongcraft commented
We could also look into playing sounds from another player, but if so, I think that should be discussed first.

2025-01-22 13:37 UTC, nicolube commented
@astei Could this be reviewed pls.

2025-02-22 16:26 UTC, 4drian3d approved these changes

2025-03-12 00:12 UTC, nicolube commented
@4drian3d Since it has been approved, can this also be merged?

2025-03-14 10:32 UTC, TheXplore commented
What is the state of this? We are currently discussing implementing this ourselves, but we would way prefer having it implemented in upstream.

2025-03-14 12:57 UTC, Timongcraft commented
Apart from maybe adding Javadoc to the RegisteredServer, **this** PR is ready from my end.

2025-03-15 14:02 UTC, TheXplore commented
@4drian3d Do you think additional Javadoc entries are required? Is there an estimate when this might get merged?

2025-04-01 00:30 UTC, nicolube commented
@electronicboy 
Sry for the ping, but what is blocking this from being merged?

2025-05-03 10:56 UTC, kezz requested changes

2025-05-03 10:56 UTC, kezz commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
Better to fail silently, that's more adventure

2025-05-03 10:56 UTC, kezz commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
If we're tracking all the entity IDs now, other emitters could be supported right? Not a requirement for this PR, just a future thought.

2025-05-03 10:56 UTC, kezz commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
Or possibly just ignore the emitter and play normally

2025-05-03 10:57 UTC, kezz commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
Also, any reason you only override play sound with an emitter?

2025-05-03 10:58 UTC, Timongcraft commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
Yea, like other players but I found out this:
> I did not add support to use other players as emitter, as custom sounds played like that will just appear like if they were coming from the player itself.

And thought it wasn't worth it, right?

2025-05-03 11:00 UTC, Timongcraft commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
> Also, any reason you only override play sound with an emitter?

Yes, because the other one indicates it uses the position of the player, which wouldn't follow it. So I moved the implemented method [here](https://github.com/PaperMC/Velocity/pull/1422/commits/6ec69dc8b3a6223f30fe32e7fe837de940dd1d0e).

2025-05-03 11:02 UTC, Timongcraft commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
But also if we would add more emitters in the future I thought it would make sense to enforce the use of the self emitter, should we really ignore it?

2025-05-03 11:08 UTC, kezz commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
That sounds like you were testing with sounds with the wrong number of channels - they definitely should follow the player.

2025-05-03 11:09 UTC, kezz commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
Ah yes, and velocity doesn't track the location so we can't use that packet. 

It's API contract for unsupported adventure methods to not throw exceptions.

2025-05-03 11:09 UTC, Timongcraft commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
wdym? I used the player entity sound packet with a entity id of another player, in I think 1.21.4, and it just acted like the sound was coming from the player I sent the packet to. But I could test again.

2025-05-03 11:10 UTC, Timongcraft commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
Alright, then I'll make it silent was well

2025-05-03 11:16 UTC, Timongcraft commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
Are null checks exempt, cause I see them in some places or should everything fail silently?

2025-05-03 11:49 UTC, Timongcraft commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
Yea, in my testing (new setup, 1.21.4) when using another player as emitter it only is played from the other player if it is 1. a vanilla sound, and 2. use the `stream` parameter like `music_disc.cat` but not `minecraft:item.goat_horn.sound.2`.
And thus I did not find it useful and too complicated to understand to include.

2025-05-06 13:51 UTC, Timongcraft commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
> +    Preconditions.checkArgument(emitter.equals(Sound.Emitter.self()), "non-self emitter not supported");
@kezz, what do you say?
(also to the other conversation below)

2025-05-13 15:12 UTC, kezz commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
If you have a stereo sound it will never play following the entity and instead will play globally. https://bugs.mojang.com/browse/MC-146721

2025-05-13 15:20 UTC, Timongcraft commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
Ah thanks, didn't know about that.
I'll test and implement it again.
Would it make sense to add that to the adventure javadoc, I'd open a pr if you want?

2025-05-13 17:16 UTC, Timongcraft commented
Even though the sound should be ignored for invalid entity ids, I still choose to test for the current server and thus require it on the receiver because afaik they are not that unique and if there's some other entity with that id exists, it could cause unwanted consequences.

2025-05-19 17:22 UTC, kezz approved these changes

2025-05-19 17:23 UTC, kezz commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
Would be a good addition to the Sound class yes.

2025-05-19 17:58 UTC, Timongcraft commented on api/src/main/java/com/velocitypowered/api/proxy/Player.java
> +   * and requires a present {@link #getCurrentServer}. Additionally, it only supports {@link Sound.Emitter#self()} for now.
> Would be a good addition to the Sound class yes.

Why the '[Sound](https://github.com/KyoriPowered/adventure/blob/1b8f5e418ebb26b12b6f3755d16bfaa7ada8a548/api/src/main/java/net/kyori/adventure/sound/Sound.java)' class instead of [the specific 'playSound' method in 'Audience'](https://github.com/KyoriPowered/adventure/blob/1b8f5e418ebb26b12b6f3755d16bfaa7ada8a548/api/src/main/java/net/kyori/adventure/audience/Audience.java#L668)?

2025-06-16 12:05 UTC, Krymonota commented
Is there any chance that this could be merged soon? I'd love to use it! :)

2025-06-16 13:19 UTC, Timongcraft commented
> Is there any chance that this could be merged soon? I'd love to use it! :)

I'd wait for 1.21.6 and see how to handle the implementation of Adventure for [the new "UI" sound category](https://www.minecraft.net/en-us/article/minecraft-1-21-6-pre-release-3).

2025-07-18 08:54 UTC, TheXplore commented
Hi, is there a current estimate when this might get merged? :)

2025-09-24 22:24 UTC, 4drian3d approved these changes
lgtm
It works quite well

2025-09-25 04:14 UTC, Timongcraft reviewed
I did not implement the Player#playSound(Sound) method as adventure defines it like this:
> Plays a sound at the location of the recipient of the sound.

Since we can't fulfill that, would it be fine to break that contract by replacing the javadoc?

https://github.com/KyoriPowered/adventure/blob/-/api/src/main/java/net/kyori/adventure/audience/Audience.java#L629C6-L631

2025-09-25 04:52 UTC, 4drian3d commented
> I did not implement the Player#playSound(Sound) method as adventure defines it like this:
> 
> > Plays a sound at the location of the recipient of the sound.
> 
> Since we can't fulfill that, would it be fine to break that contract by replacing the javadoc?
> 
> https://github.com/KyoriPowered/adventure/blob/-/api/src/main/java/net/kyori/adventure/audience/Audience.java#L629C6-L631

_I'll be honest, I tried this pull request for 30 minutes without knowing why the sound wasn't playing, since stopSound was working for me, until I saw that the `#playSound(Sound)` method wasn't implemented_

From a plugin developer's perspective, this method should be implemented, but from a contract compliance perspective, it's okay not to implement it as required by the contract. With this in mind, good documentation at https://docs.papermc.io/velocity/dev/pitfalls/#audience-operations-are-not-fully-supported would suffice, so I am now reverting my change

2025-09-25 13:38 UTC, Timongcraft commented
What do you say about stuffing override dialog api methods into this pr as well for documentation purposes?

2025-09-28 23:46 UTC, 4drian3d approved these changes

2025-09-29 14:04 UTC, RealBauHD approved these changes

2025-09-29 14:22 UTC, merged