Invocation Source API
PaperMC/Velocity pull request #1467
Opened 2024-12-03 21:36 UTC by Owen1212055

Allows proxies to detect if a command is executed from an unsigned/signed/api source.

This is useful because it allows commands executed from the player manually or by clicking on a chat message to be controlled.

2024-12-03 21:54 UTC, powercasgamer requested changes

2024-12-03 21:54 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/command/CommandExecuteEvent.java
> +  public InvocationSource getInvocationSource() {
```suggestion
  public @NonNull InvocationSource getInvocationSource() {
```

2024-12-03 22:03 UTC, Timongcraft commented
Why do pre 1.19.1 messages also have a unknown source, wouldn't unsigned make more sense?

2024-12-03 22:13 UTC, Owen1212055 commented
> Why do pre 1.19.1 messages also have a unknown source, wouldn't unsigned make more sense?

It made most sense to me to differentiate it, although I am open to change for that here.

2024-12-03 22:19 UTC, Timongcraft commented
> It made most sense to me to differentiate it, although I am open to change for that here.

I just thought it would be good to know if it is unsigned, but this also makes sense, but i guess if you really need the information you can also just look at the player's protocol version.

2024-12-03 23:20 UTC, kashike requested changes

2024-12-03 23:20 UTC, kashike commented on api/src/main/java/com/velocitypowered/api/event/command/CommandExecuteEvent.java
> +  public enum InvocationSource {
This is less of a "source" and more of a "type".
```suggestion
  public enum InvocationType {
```

2024-12-03 23:57 UTC, kashike approved these changes

2024-12-03 23:58 UTC, Owen1212055 commented
@Timongcraft Some significant changes have been done, feedback appreciated.

2024-12-04 05:47 UTC, Timongcraft commented on api/src/main/java/com/velocitypowered/api/event/command/CommandExecuteEvent.java
> +    SIGNED_WITHOUT_ARGS,
Shouldn't the javadoc say it's a signed source, because it comes from a signed context?

2024-12-04 05:51 UTC, Owen1212055 commented on api/src/main/java/com/velocitypowered/api/event/command/CommandExecuteEvent.java
> +    SIGNED_WITHOUT_ARGS,
yes!

2024-12-04 05:52 UTC, Timongcraft approved these changes

2024-12-04 07:33 UTC, powercasgamer requested changes

2024-12-04 07:33 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/command/CommandExecuteEvent.java
> +  private InvocationInfo invocationSource;
```suggestion
  private InvocationInfo invocationInfo
```

2024-12-04 07:33 UTC, powercasgamer commented on api/src/main/java/com/velocitypowered/api/event/command/CommandExecuteEvent.java
> +   * @return invocation source
```suggestion
   * @return invocation info
```
?

2024-12-04 16:22 UTC, electronicboy approved these changes

2024-12-04 17:36 UTC, kashike approved these changes

2024-12-04 17:36 UTC, merged