Handle exceptions relating to CompletableFuture operations
PaperMC/Velocity pull request #376
Opened 2020-10-26 18:00 UTC by A248

Solves #374 by adding `exceptionally` where CompletableFutures are not otherwise chained or returned. The last future in a chain, if it is not awaited, must have some sort of exception handler.

2020-10-26 21:28 UTC, astei requested changes
You have failed to convince me there exists a real problem to be addressed here, something I  brought up in #374. You've convinced me the pitfall _exists_ but you've failed to convince me that this quirk of `CompletableFuture` is an actual problem as it is used in Velocity, particularly when paired with `fire()` (which, I have checked, and unless there is some sort of bizarro `Throwable` getting thrown, there is no exception thrown). This, in my opinion, pollutes all async code with a condition to deal with a concern that, in my eyes, is currently _purely theoretical_.

Come back to me with a _real_ problem that this patch fixes and I will definitely merge this in.

2020-10-26 21:40 UTC, A248 commented
Not following best practices is a real problem, one which is as real as the bugs it leads to.

Consider:

```java
try {
  // some operation
} catch (Throwable ignored) {}
```

You don't write synchronous code this way. It would be ludicrous. Even if you knew your current code did not throw any exceptions, it makes no sense to swallow them.

What happens when you change the body of the try block, and it starts to throw? You'll receive little indication something is wrong aside from the fact that bits and pieces of your code are no longer running, because it abruptly and silently terminated due to an exception. Or, what happens if your code doesn't throw an exception most of the time, but there are those edge cases and race conditions in which it does? Either way, hiding all Throwables is a terrible way to go.

The equivalent of the empty catch block in asynchronous code is failing to attach an exception handler to the last CompletableFuture in a chain:

```java
CompletableFuture.runAsync(() -> {
  // some operation
});
```

This is just as deadly and just as potent as a synchronous empty catch block. I would add just as hard to debug, except that it is *harder* to debug considering the nature of debugging asynchronous interactions.

It's a little bit of extra code on the tail end of your CompletableFutures to prevent a whole host of silent future problems.

2020-10-26 21:47 UTC, astei approved these changes
I'll merge this in but I still question the need for it.

2020-10-26 21:47 UTC, merged

2020-10-30 11:00 UTC, astei commented
You were right, I was wrong. Some legitimate bugs were uncovered by this. Thank you so much @A248.