Add 1.16.5
PaperMC/Velocity pull request #437
Opened 2021-03-06 14:05 UTC by DoctaEnkoda

This is frankly not an important update, even useless, but at least to display the status of servers via minecraft or other, showing that the 1.16.5 is supported will not hurt. Especially since not everyone knows that the 1.16.4 and the 1.16.5 are identical level connection protocol

2021-03-06 14:11 UTC, DoctaEnkoda commented
![image](https://user-images.githubusercontent.com/26461373/110209717-3b489380-7e8e-11eb-87d6-3730397661df.png)

2021-03-06 15:04 UTC, Xernium requested changes
Doing this has the adverse side-effect of duplicating the packet state registry for these versions. However your point is taken. I will see what can be done about this minor inconvenience.

2021-03-06 15:39 UTC, Xernium commented
https://github.com/VelocityPowered/Velocity/commit/92e8aa0a374458d196de914aaaeb9a0fd6811480 for a first attempt. I want @astei to look over this

2021-03-11 08:32 UTC, astei commented
92e8aa0 is the most probable path for adding this. Thanks for PRing anyway.

2021-03-11 08:32 UTC, closed without merging