German translations
PaperMC/Velocity pull request #460
Opened 2021-04-17 16:25 UTC by StealWonders

Follow up of https://github.com/VelocityPowered/Velocity/pull/261

This pull request basically implements all the provided strings in German. 
If other fluent speakers have any ideas for better translations I'm open for discussion :-)

2021-04-19 10:30 UTC, KennyTV requested changes

2021-04-19 10:30 UTC, KennyTV commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_de_DE.properties
> +velocity.command.server-too-many=Es sind zu viele Server eingerichtet. Verwenden Sie die Tabulatorvervollständigung, um alle verfügbaren Server aufzulisten.
This is the only place you used `Sie` and I've never seen anyone actually use the full word "Tabulator" 👀.
```suggestion
velocity.command.server-too-many=Es sind zu viele Server eingerichtet. Verwende die Tabvervollständigung, um alle verfügbaren Server aufzulisten.
```

2021-04-19 10:30 UTC, KennyTV commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_de_DE.properties
> +velocity.error.online-mode-only=Du bist nicht in deinem Minecraft Konto eingeloggt. Wenn du in deinem Minecraft Konto eingeloggt bist, versuche dein Minecraft Client neu zu starten.
```suggestion
velocity.error.online-mode-only=Du bist nicht in deinem Minecraft Konto eingeloggt. Wenn du in deinem Minecraft Konto eingeloggt bist, versuche deinen Minecraft Client neu zu starten.
```

2021-04-19 10:30 UTC, KennyTV commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_de_DE.properties
> +velocity.command.server-tooltip-offer-connect-server=Klicke, um sich mit diesem Server zu verbinden
```suggestion
velocity.command.server-tooltip-offer-connect-server=Klicke, um dich mit diesem Server zu verbinden
```

2021-04-19 13:24 UTC, KennyTV approved these changes
👍

2021-04-19 13:50 UTC, aurorasmiles requested changes

2021-04-19 13:50 UTC, aurorasmiles commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_de_DE.properties
> +velocity.command.server-tooltip-player-online={0} spieler online
```suggestion
velocity.command.server-tooltip-player-online={0} Spieler online
```

2021-04-19 13:50 UTC, aurorasmiles commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_de_DE.properties
> +velocity.command.server-tooltip-players-online={0} spieler online
```suggestion
velocity.command.server-tooltip-players-online={0} Spieler online
```

2021-04-19 13:50 UTC, aurorasmiles commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_de_DE.properties
> +velocity.command.reload-failure=Die Velocity-Konfiguration konnte nicht neu geladen werden. Prüfe die Konsole auf weitere Details.
```suggestion
velocity.command.reload-failure=Die Velocity-Konfiguration konnte nicht neu geladen werden. Prüfe die Konsole für weitere Details.
```

2021-05-09 08:49 UTC, astei commented
Can you update your translations with the new messages in 1e8454c7? Thanks!

2021-05-09 21:38 UTC, aurorasmiles approved these changes

2021-05-10 06:09 UTC, astei commented
[Imported into Crowdin](https://crowdin.com/project/velocity/de)

2021-05-10 06:09 UTC, closed without merging