Bulgarian translation
PaperMC/Velocity pull request #475
Opened 2021-04-19 11:53 UTC by MrIvanPlays

2021-04-19 13:12 UTC, Proximyst requested changes

2021-04-19 13:12 UTC, Proximyst commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.already-connected=Вече сте свързан към този сървър!
Fix your line endings

2021-04-19 13:45 UTC, DoNotSpamPls requested changes
General grammar mistakes. Overall, it's a good translation.

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.already-connected-proxy=Вече сте свързан към това прокси!
"свързани" вместо "свързан"

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.already-connecting=Вече се опитваме да Ви свържем към сървър!
В оригиналния файл се има предвид, че самия играч вече се опитва да се свърже, т.е. трябва да стане "Вече са опитвате да се свържете към сървър!"

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.connecting-server-error=Не можахме да Ви свържем към {0}. Моля, опитайте по-късно.
Мое лично мнение е, че "Не успяхме да Ви свържем" ще е по-удачно.

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.internal-server-connection-error=Възникна вътрешна грешка при сървърната връзка.
Тук има разминаване, или ще ползваш "възникна грешка" (което според мен е по-добре) или "получихме грешка"
Също така, по-нагоре използваш "свързан към {0}", би следвало и тук да е така.

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.player-connection-error=Възникна грешка с вашата връзка.
Избери дали ще използваш "при връзката" или "с връзката"

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.logging-in-too-fast=Опитвате се да влизате твърде бързо, моля изчакайте малко време.
L22 - "Моля, опитайте по-късно.", ползвай същото и тук.
Можеш да разделиш двете изречения с тире.

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.online-mode-only=Не сте стартирали играта със закупения Ви Minecraft акаунт. Ако сте стартирали играта със закупен Minecraft акаунт, пробвайте рестарт на играта и на лаунчера.
Тук допускаш, че играча не си е купил играта. Макар това да е факт в България, превода би трябвало да е безпристрастен. По-добър вариант ще е 

"Не сте влезли в своя Minecraft акаунт. Ако вече сте го направили, опитайте да рестартирате играта и опитайте отново."

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.modern-forwarding-needs-new-client=Сървъра, в който опитахте да влезете, изисква Minecraft 1.13+.
"Този сървър е съвместим само с Minecraft 1.13 или по-нова версия."

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.modern-forwarding-failed=Сървъра не изпрати заявка за изискване на информация към проксито. Моля, убедете се, че сървъра Ви е настроен за Velocity.
"Сървъра Ви"
"заявка за препращане на информация"
"за работа с Velocity"

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-current-server=Вмомента сте свързан към {0}.
липсва интервал

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-too-many=Има прекалено много регистрирани сървъри. Използвайте TAB за да видите всички.
"Използвайте TAB, за да видите всички налични сървъри."

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-tooltip-current-server=Вмомента сте свързан към този сървър
липсва интервал

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-tooltip-offer-connect-server=Натиснете с ляв бутон на мишката, за да Ви свържем към този сървър
Това е tooltip, съответно изречението трябва да е по-кратко.

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.glist-view-all=За да видите всички играчи на сървъри, използвайте /glist all.
"За да видите всички играчи, разпреледени по сървъри, използвайте /glist all"

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.reload-failure=Не можахме да презаредим настройките на Velocity. Моля, проверете конзолата, за повече информация.
"Не успяхме"
Няма нужда от запетая след конзолата

2021-04-19 13:45 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.version-copyright=Всички права запазени 2018-2021 {0}. {1} е лицензирана под условията на GNU General Public License v3.
Има доста голяма разлика между "Авторско право" (какъвто е превода на copyright) и "Всички права запазени". Предвид че това е FOSS проект, няма как да е със запазени всички права 😃 

Второто изречение започва с Velocity, предполагам че трябва да е мъжки род.

2021-04-19 14:00 UTC, MrIvanPlays commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.online-mode-only=Не сте стартирали играта със закупения Ви Minecraft акаунт. Ако сте стартирали играта със закупен Minecraft акаунт, пробвайте рестарт на играта и на лаунчера.
Според мен моя вариант е по-добър точно заради факта, който ти посочи. Къде пише, че трябва да е безпристрастен? Това да не е нещо от типа на бабините дивотини? "Баба ти Пенка преди 450 години измислила, че като се погребва човек трябва да се хвърля пясък докато се спуска ковчега" и след това всички така го правят.

2021-04-19 14:05 UTC, MrIvanPlays commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-tooltip-offer-connect-server=Натиснете с ляв бутон на мишката, за да Ви свържем към този сървър
"Натиснете, за да Ви свържем към този сървър" или "Кликнете, за да Ви свържем към този сървър" 
Според мен "Кликнете" звучи по-добре, но е чуждица и се опитвам да избягвам чуждици

2021-04-19 15:07 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-tooltip-offer-connect-server=Натиснете с ляв бутон на мишката, за да Ви свържем към този сървър
"Натиснете" би трябвало да е ОК

2021-04-19 15:09 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.online-mode-only=Не сте стартирали играта със закупения Ви Minecraft акаунт. Ако сте стартирали играта със закупен Minecraft акаунт, пробвайте рестарт на играта и на лаунчера.
Добре, може би "безпристрастен" беше грешната дума, но идеята ми беше, че при превод не би трябвало да се добавя или премахва смисъл от изречението. В случая това го има, което не е добре.

2021-04-19 15:10 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-too-many=Използвайте TAB, за да видите всички налични сървъри.
Къде отиде първото изречение? 😦

2021-04-19 15:15 UTC, MrIvanPlays commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.server-too-many=Използвайте TAB, за да видите всички налични сървъри.
Помислих, че го искаш само така. bruh moment

2021-04-19 15:21 UTC, MrIvanPlays commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.online-mode-only=Не сте стартирали играта със закупения Ви Minecraft акаунт. Ако сте стартирали играта със закупен Minecraft акаунт, пробвайте рестарт на играта и на лаунчера.
> че при превод не би трябвало да се добавя или премахва смисъл от изречението. В случая това го има, което не е добре.

Защо мислиш така? Много добре знаеш какво става в БГ сървърите. И аз съм бил developer в БГ сървър, и ти си бил. BG Multiplayer minecraft community-то се състои предимно от лапета. Като им пляснеш едно "Не сте влезли в своя Minecraft акаунт" ще почнат "admine admine zashto mi pishe che ne sum vlqzul v moq minecraft akaunt". Като има допълнително обяснение според мен ще улесни сървърите доста повече.

2021-04-19 15:28 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.online-mode-only=Не сте стартирали играта със закупения Ви Minecraft акаунт. Ако сте стартирали играта със закупен Minecraft акаунт, пробвайте рестарт на играта и на лаунчера.
Това съобщение така или иначе би излязло, само ако сървъра е в online mode. Ако е сървър където им се занимава с лапета, едва ли ще са го оставили включен. 😃

2021-04-19 15:36 UTC, MrIvanPlays commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.error.online-mode-only=Не сте стартирали играта със закупения Ви Minecraft акаунт. Ако сте стартирали играта със закупен Minecraft акаунт, пробвайте рестарт на играта и на лаунчера.
Имаш право. Alright then, ще го променим.

2021-04-19 15:44 UTC, DoNotSpamPls approved these changes
@astei should be ready for merge

2021-05-09 08:48 UTC, astei commented
Can you update your translations with the new messages in 1e8454c7? Thanks!

2021-05-27 05:47 UTC, MrIvanPlays commented
sorry for slow resp, been busy with other stuff.
@DoNotSpamPls please review the new messages kthx

2021-05-27 07:56 UTC, DoNotSpamPls requested changes

2021-05-27 07:56 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.dump-send-error=Възникна комуникационна грешка със сървърите на Velocity. Сървърите може да не са налични временно или има проблем с мрежовите настройки. Ще откриете повече информаци
"Възникна грешка при комуникацията..." е по-удачно, не знаем каква точно е грешката

"..може временно да не са налични, или да имате проблем с мрежовите настройки" за да стане ясно, че проблема с настройките може да е при локалния сървър

"Вашето Velocity proxy" честно казано и оригиналния превод леко бърка тук, но нека да стане ясна разликата - много сървъри стават иначе

2021-05-27 07:56 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.dump-offline=Вероятната причина е, че имате невалидни системни DNS настройки или нямате достъп до интернет
"Вероятна причина: Невалидни системни DNS настройки или липса на Интернет връзка."

2021-05-27 07:56 UTC, DoNotSpamPls commented on proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages_bg_BG.properties
> +velocity.command.dump-server-error=Възникна грешка на сървърите на Velocity и доклада не може да бъде завършен. Моля, свържете се с разработчиците на Velocity относно този проблем и осигурете детайли
"при сървърите на Velocity"
"Моля, уведомете разработващия екип на Velocity" понеже в по-горното съобщение споменахме разработчик
"детайли за грешката"

2021-05-27 17:59 UTC, DoNotSpamPls approved these changes

2021-09-01 09:08 UTC, astei commented
Closing due to lack of action. If you want to revive this, use Crowdin.

2021-09-01 09:08 UTC, closed without merging