Expose CommandMeta in CommandManager and add a ref to the plugin instance
PaperMC/Velocity pull request #544
Opened 2021-07-15 14:53 UTC by FrankHeijden

Instead of having a reference to the plugin instance, a string with the plugin id might also be a nice idea -- but not sure which one would be preferred.

2021-10-29 15:46 UTC, astei requested changes
Sorry for leaving this too dry for so long. I've been busy.

2021-10-29 15:46 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandManager.java
> +    this.commandMeta = Maps.newConcurrentMap();
`new ConcurrentHashMap<>()`

2021-10-30 16:07 UTC, hugmanrique reviewed
I'd prefer the plugin return types being `@Nullable Object` over optionals, Also, why do we only register the first alias? I would add all them to the map (to follow the javadoc). Otherwise LGTM.

2021-10-31 20:19 UTC, astei requested changes

2021-10-31 20:19 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandManager.java
> +        commandMetas.remove(metaAlias);
Nit: perhaps this should check if the meta is the same as the primary alias with `Map.remove(key, onlyIfValue)`.

2021-10-31 20:19 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandMeta.java
> +    private Object plugin;
```suggestion
    private @MonotonicNonNull Object plugin;
```

2021-10-31 20:19 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandManager.java
> +          commandMetas.remove(metaAlias);
Needs to check if the meta saved in the alias is equal to the original.

2021-10-31 20:23 UTC, astei approved these changes

2021-10-31 20:23 UTC, merged

2021-10-31 22:50 UTC, hugmanrique commented
This should unconditionally remove the meta since we create a mapping from command aliases (not commands) to metas. As it stands, one may register the same command with two aliases, unregister one alias, and `getCommandMeta("otherAlias")` will incorrectly return `null` (doesn't follow the javadoc). https://github.com/VelocityPowered/Velocity/pull/544/files#diff-00c49e74f0fbdfecca0759479a72ed71560803e34e2ef3e0b4b6f686d69a3cfcR160

2021-10-31 22:54 UTC, astei commented
> This should unconditionally remove the single mapping since we create a mapping from command aliases (not commands) to metas. As it stands, one may register the same command with two aliases, unregister one alias, and `getCommandMeta("otherAlias")` will incorrectly return `null` (doesn't follow the javadoc). https://github.com/VelocityPowered/Velocity/pull/544/files#diff-00c49e74f0fbdfecca0759479a72ed71560803e34e2ef3e0b4b6f686d69a3cfcR160

This is also incorrect - `unregister(String)` unregisters a _single_ alias. Perhaps we should provide an `unregister(CommandMeta)` as well to unregister every alias pointing to a given `CommandMeta`.

2021-10-31 23:00 UTC, hugmanrique commented
That's my point, right now `unregister("a")` will unregister the meta mappings for any other aliases for the same command (maybe I misunderstood your message, sorry if so 😛).

On `unregister(CommandMeta)`, that's a good idea.

2021-10-31 23:05 UTC, astei commented
Fixed that in 0b0c36d, thanks!