Don't allow illegal characters
PaperMC/Velocity pull request #580
Opened 2021-10-02 15:18 UTC by Foorcee

The Minecraft server will not accept a chat packet from a player that contains an invalid character. 
If the chat packet is handled on Velocity, such as a command, it doesn't check if the message is valid.

2021-10-02 17:41 UTC, hugmanrique commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
> +  private boolean isAllowedCharacter(char c) {
Nice catch! Could you document this function noting the source (apart from the client source) like wiki.vg for the allowed characters?

2021-10-02 17:46 UTC, hugmanrique commented
I'm not 100% on how the translations currently work, but I think you also need to add the corresponding entry to https://github.com/VelocityPowered/Velocity/blob/dev/3.0.0/proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages.properties

2021-10-02 19:00 UTC, Foorcee commented
I have added the translation. I am not sure how the translation system works.

2021-10-02 19:00 UTC, astei requested changes

2021-10-02 19:00 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
> +    for (int i = 0; i < msg.length(); i++) {
Please make this a unit test, ideally by extracting this out into a static method that just does the character validity check.

2021-10-02 19:55 UTC, Foorcee commented
@astei What should I do with the new translation?

2021-10-02 21:04 UTC, astei commented
Don't worry about it, I'll handle it.

2021-10-03 18:40 UTC, astei requested changes

2021-10-03 18:40 UTC, astei commented on proxy/src/test/java/com/velocitypowered/proxy/util/CharacterUtilTest.java
> +
This test is insufficient. We should also make sure the check does not reject strings with non-ASCII characters in them, such as CJK (Chinese/Japanese/Korean).

2021-10-03 20:09 UTC, merged