Redirect player without message
PaperMC/Velocity pull request #581
Opened 2021-10-03 11:01 UTC by Foorcee

Fixes #392

I don't know if this is the best solution, but I tried not to change the existing behavior as much as possible. 
I also improved/corrected the javadocs.

Overall it would be best if the message could be set based on the connection state. Since that would require more redesigning, so this could be best added to the polymer.

Feedback is welcome

2021-10-03 20:10 UTC, astei commented
Instead of adding another parameter to the `RedirectPlayer`, couldn't we just do a check to see if the message is `Component.empty()` and just don't print a message in this case?

2021-10-03 20:55 UTC, Foorcee commented
That was basically my first idea as well.  I just thought it would be inconsistent. If the message is null, the kick reason is sent as a message. If empty, no message is sent and otherwise a message is sent again. But this is the simplest solution, if it fits so I would change it again.

2021-10-08 21:55 UTC, astei requested changes

2021-10-08 21:55 UTC, astei commented on api/src/main/java/com/velocitypowered/api/event/player/KickedFromServerEvent.java
> +    @Deprecated
Why is this deprecated?

2021-10-08 21:55 UTC, astei commented on api/src/main/java/com/velocitypowered/api/event/player/KickedFromServerEvent.java
> +    public static RedirectPlayer connect(RegisteredServer server) {
Probably not necessary, a note on the two-parameter constructor would be sufficient, such as:

```
* Use {@code Component.empty()} to skip sending any messages to the player.
```

2021-10-10 00:31 UTC, astei approved these changes

2021-10-10 00:32 UTC, merged