Migrate buildSrc plugins to build-logic
PaperMC/Velocity pull request #986
Opened 2023-03-26 22:12 UTC by alexstaeding

As mentioned in #983, this PR migrates all `buildSrc` plugins to a `build-logic` project.

Everything should be functionally identical to the way it worked previously with the following exceptions:

- The application of the publish plugin is done individually in the api and native projects. Previously, the following if-condition in the velocity publish plugin https://github.com/PaperMC/Velocity/blob/36cc2bde23e7d50545c04b4060a52f3e6b461368/buildSrc/src/main/kotlin/com/velocitypowered/script/VelocityPublishPlugin.kt#L36 would lead to the api and native project to being published. I'm not sure if publishing the native project is intended, but that can be fixed easily.

- I have centralized the repository declaration in `settings.gradle.kts` and enabled `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)`

2023-03-26 23:46 UTC, kashike commented on build-logic/src/main/kotlin/velocity-publish.gradle.kts
> +            val base = "https://papermc.io/repo/repository/maven"
```suggestion
            val base = "https://repo.papermc.io/repository/maven"
```

2023-06-16 16:59 UTC, powercasgamer requested changes

2023-06-16 16:59 UTC, powercasgamer commented on settings.gradle.kts
> +
```suggestion
```

2023-06-16 16:59 UTC, powercasgamer commented on build-logic/src/main/kotlin/velocity-publish.gradle.kts
> +                url.set("https://www.velocitypowered.com")
```suggestion
                url.set("https://papermc.io/software/velocity")
```

velocitypowered.com redirects here

2023-06-21 14:03 UTC, alexstaeding commented
Applied suggested fixes for typos and fixed conflicts with base (dev/3.0.0)

2023-06-21 15:18 UTC, powercasgamer approved these changes

2023-07-19 15:05 UTC, 4drian3d approved these changes

2023-07-19 15:27 UTC, powercasgamer approved these changes

2023-10-27 20:00 UTC, astei commented
Publishing the native is intentional, it was done for [Krypton](https://github.com/astei/krypton)

2023-10-27 20:05 UTC, astei commented
Manually rebased and merged with 24ed83dcadcf55e8831d3f6fa84ab89222f6b222 - thanks for this

2023-10-27 20:05 UTC, closed without merging