feat: implement click callback [WIP]
PaperMC/Velocity pull request #989
Opened 2023-03-30 07:43 UTC by powercasgamer

2023-03-30 08:50 UTC, kashike requested changes

2023-03-30 08:50 UTC, kashike commented on proxy/velocity.toml
Remove this file from your PR.

2023-04-11 16:00 UTC, 4drian3d commented on proxy/src/main/java/com/velocitypowered/proxy/command/builtin/VelocityCommand.java
> +    private static final Logger logger = LogManager.getLogger(Callback.class);
This Logger creation is unnecessary, it is not used anywhere.

2023-04-11 19:59 UTC, 4drian3d approved these changes

2023-04-19 21:49 UTC, astei requested changes

2023-04-19 21:49 UTC, astei commented on proxy/src/main/java/com/velocitypowered/proxy/provider/ClickCallbackProviderImpl.java
> +  }
I'm really not a big fan of this approach.

* We already have an expiring cache, Caffeine. Why have an eviction task running every 5 milliseconds?
* The `HashMap` used here is not thread safe. Velocity is a multi-threaded environment. This kind of implementation would make sense with Paper, with a single server thread, but it won't fly here.

For this reason I am not willing to sign off on this implementation unless these issues were resolved.

2023-04-20 06:32 UTC, powercasgamer commented
closing due to https://github.com/PaperMC/Velocity/tree/feat/click-callback-provider ?

2023-04-20 06:32 UTC, closed without merging